**The goal of first three problems will be to write the derivative of a polynomial in three steps, so we can write:**

In [4]:
print(parse_polynomial('9 + 8*x + 5*x**2 + 15*x**3'))
print(d_poly(parse_polynomial('9 + 8*x + 5*x**2 + 15*x**3')))
print(write_polynomial(d_poly(parse_polynomial('9 + 8*x + 5*x**2 + 15*x**3'))))

[ 9  8  5 15]
[ 8 10 45]
8 + 10*x + 45*x**2


# Problems
---
### Derivative of a polynomial
A polynomial $p(x) = a_0 + a_1 x+\dots + a_{n-1} x^{n-1}+ a_n x^n$ can be saved as `np.array([a_0,a_1,\dots,a_n])`. The derivative of a polynomial is another polynomial, whose coefficients are given by:
```python
def d_poly(p: np.array) -> np.array:
    """
    Returns the derivative of a polynomial.
    >>> d_poly(np.array([-8,0,2,3]))
    array([0, 4, 9])
    >>> d_poly(np.array([0,-8,5,2,-1]))
    array([-8, 10,  6, -4])
    """
```

In [1]:
import numpy as np 

def d_poly(p: np.array) -> np.array:
    """
    Returns the derivative of a polynomial.
    >>> d_poly(np.array([-8,0,2,3]))
    array([0, 4, 9])
    >>> d_poly(np.array([0,-8,5,2,-1]))
    array([-8, 10,  6, -4])
    """
    order = len(p) - 1
    return np.array([p[i]*i for i in range(1, order+1)])

import doctest
doctest.testmod()

TestResults(failed=0, attempted=2)

---
### Parsing polynomial from a string (string to array)
Save any polynom from the standard input to numpy array. Assume all powers are present.
For example: 
```python
def parse_polynomial(input: str) -> np.array:
    """
    Parses a polynomial string and returns the coefficients as a numpy array.

    Examples:
        >>> parse_polynomial('9 + 8*x + 5*x**2 + 0*x**3 +15*x**4')
        array([ 9,  8,  5,  0, 15])
    """
```

In [2]:
import numpy as np

def parse_polynomial(input: str) -> np.array:
    """
    Parses a polynomial string and returns the coefficients as a numpy array.

    Examples:
        >>> parse_polynomial('9 + 8*x + 5*x**2 + 0*x**3 +15*x**4')
        array([ 9,  8,  5,  0, 15])
    """
    terms = input.split('+')
    terms = [term.split('*') for term in terms]
    coeffs = np.array([int(term[0]) for term in terms])
    return coeffs

doctest.testmod()

TestResults(failed=0, attempted=3)

---
### Writing a polynomial to string (array to string)
Do the inverse function to `parse_polynomial`, i.e. write a function accepting `np.array` polynom representation and returning a string.  
```python
def write_polynomial(p: np.array) -> str:
    """
    Returns a string representation of a polynomial.

    Examples:
        >>> write_polynomial(np.array([ 9,  8,  5,  0, 15]))
        '9 + 8*x + 5*x**2 + 0*x**3 + 15*x**4'
    """
```

In [3]:
def write_polynomial(p: np.array) -> str:
    """
    Returns a string representation of a polynomial.

    Examples:
        >>> write_polynomial(np.array([ 9,  8,  5,  0, 15]))
        '9 + 8*x + 5*x**2 + 0*x**3 + 15*x**4'
    """
    terms = [str(p[0]),f"{p[1]}*x"]
    for i in range(2,len(p)):
        terms.append(f"{p[i]}*x**{i}")
    return ' + '.join(terms)

doctest.testmod()

TestResults(failed=0, attempted=4)

---
### sqrt(q) using Newton's method
Tangent line to the function at point $x_0$ is given by:
$$
y = f(x_0) + f'(x_0)(x-x_0).
$$
The point $x_1$, where such a line intersects $y=0$ is given by:
$$
f(x_0) + f'(x_0)(x_1-x_0) = 0,
$$
which has a solution:
$$
x_1 = x_0 - \frac{f(x_0)}{f'(x_0)}.
$$
Analogically, we can find $x_2$:
$$
x_2 = x_1 - \frac{f(x_1)}{f'(x_1)},
$$
etc. We see that now we can use this method iteratively to find the root of any function, because $\{x_n\}$ is a series converging to this point.


For example, to calculate $\sqrt q$, we set $f(x)=x^2-q$, because its root is at $x=\sqrt q$. The derivative is $f'(x) = 2x$, leading to iterations in the form:
$$
x_{n+1} = x_n - \frac{f(x_n)}{f'(x_n)} = \frac{x_n + \frac{q}{x_n}}{2}.
$$
Good initial guess might be $x_0 = q/2$.

In [37]:
from math import sqrt

def my_sqrt(x: float, iterations: int) -> float:
    """Calculate the square root of x using Newton's method. 
    Precision is set by the number of iterations."""
    # initial guess, controls to which minima the algorithm converges
    guess = x/2
    for i in range(iterations):
        guess = (guess + x/guess)/2
    return guess

# print the result
num = 42
print("my_sqrt(2) =", my_sqrt(num, 4))
# check the result
print("error =", my_sqrt(num, 4) - sqrt(num))

my_sqrt(2) = 6.481218587467409
error = 0.0004778890595487084


# Problematic problems
---
### Extending parse_polynomial()
Rewrite the function `parse_polynomial` to accept polynomial with missing power. For example `parse_polynomial('9 + 8*x + 5*x**2 +15*x**4')` should return `array([ 9,  8,  5,  0, 15])`.